drop table if exists coupons cascade
create table coupons (id bigint generated by default as identity, code varchar(255), discount numeric(38,2), exp_date date, primary key (id))

drop table if exists roles cascade
drop table if exists users cascade
drop table if exists user_role cascade
create table roles (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id))
create table users (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id))